### ISSUE TITLE
js-beautify Not Install!  Error

### ISSUE THREAD

**Issue by zinminphy0** [pikpikcu/XRCross#10]
i actually installed js-beautify and i need to fix this error

![error](https://user-images.githubusercontent.com/63828270/90117229-a0873c80-dd24-11ea-8e2f-dc720b4470e7.png)
![install](https://user-images.githubusercontent.com/63828270/90117270-ae3cc200-dd24-11ea-8374-66c994b65367.png)
![2020-08-13_05-17](https://user-images.githubusercontent.com/63828270/90117285-b3017600-dd24-11ea-98dd-a42ecae78549.png)

**Comment by pikpikcu** [comment]
Hello @zinminphy0

thank you for open issues please update again!
