### ISSUE TITLE
Run GAU once, then grep the output into files

### ISSUE THREAD

**Issue by uBadRequest** [pikpikcu/XRCross#3]
I don't suggest running GAU over and over again for the same domain. You should just pipe the raw output from GAU to a file and grep that.

https://github.com/pikpikcu/XRCross/blob/3d54fa1a99211a8dc3c81ad4d8b09d0b25dc8b25/XRCross#L48-L61

**Comment by pikpikcu** [comment]
@uBadRequest 
ok thank you for the advice
