### ISSUE TITLE
Readme file needs to be modified

### ISSUE THREAD

**Issue by harsim09** [pikpikcu/XRCross#4]
Hi,
As all the dependent libraries are compiled with go 1.14.2 version, if there is some other version on users' system. The system gives error related to Go version mismatch which is not descriptive.

I would like to update the readme file to mention the "Go" version required and possible solutions to the errors that are faced.

Thanks,
Harry

**Comment by harsim09** [comment]
Secondly, I also like to add that , it checks for all modules at ~/go/bin path, which is generally the $GOPATH value. But some users might have a different value in $GOPATH variable as well which was in my case. So this also needs to be mentioned in the readme file.

elif [ ! -f ~/go/bin/subfinder ];

**Comment by pikpikcu** [comment]
@harsim09  
thank you bro for providing a good solution.

**Comment by harsim09** [comment]
Hi Brother,

I have made the changes to README file. Added a section related to Go dependency. Please review and let me know if any changes are needed.

Best regards,
Harry

**Comment by harsim09** [comment]
Hi Bro,

Can you help me in taking a subdomain over on cloudflare. I have made the CNAME entry but still the routing is not happening. Do you have experience in taking over subdomains?

**Comment by pikpikcu** [comment]
https://t.me/WongNdes0

DM me

Pada tanggal Kam, 18 Jun 2020 21.36, harsim09 <notifications@github.com>
menulis:

**Comment by harsim09** [comment]
Hi, 

Can you please tell me how to message you.
