### ISSUE TITLE
Blind SSRF testing log error

### ISSUE THREAD

**Issue by ltiisidii** [pikpikcu/XRCross#6]
I get this error:

Start [ Blind SSRF testing...]
sed: can't read site.com/ssrf/site.com-ssrf2.txt: No such file or directory
./XRCross: line 69: site.com/ssrf/site.com-ssrf3.txt: No such file or directory

Success Saved:[site.com/site.com-ssrf3.txt]

on line 67 save the file in $ output / $ site-ssrf2.txt
but on line 68 look for it in $ output / ssrf / $ site-ssrf2.txt

this is correct?

**Comment by pikpikcu** [comment]
hey @ltiisidii 
thank you for the notification, I've fixed it, let me know if there is any problem.

> I get this error:
> 
> Start [ Blind SSRF testing...]
> sed: can't read site.com/ssrf/site.com-ssrf2.txt: No such file or directory
> ./XRCross: line 69: site.com/ssrf/site.com-ssrf3.txt: No such file or directory
> 
> Success Saved:[site.com/site.com-ssrf3.txt]
> 
> on line 67 save the file in $ output / $ site-ssrf2.txt
> but on line 68 look for it in $ output / ssrf / $ site-ssrf2.txt
> 
> this is correct?

**Comment by ltiisidii** [comment]
./XRCross -u site.com

finish running with site.com-ssrf3.txt :D
